export const CAREERS = [
  {
    position: "Staff IT",
    company: "Pt. Gisara Tantra Berkarya",
    logo: "/images/careers/gtb.webp",
    location: "Magelang, Indonesia",
    location_type: "Onsite",
    type: "Full-time",
    start_date: "2025-07",
    end_date: "2025-12",
    industry: "Manufacture",
    link: "https://www.gisaratantraberkarya.com/",
    responsibilities: [
      "Record and manage company IT assets (hardware inventory list, software licenses, and warranty periods).",
      "Managed and ensure all hardware (computers, laptops, printers, scanners, CCTV, routers) functions optimally.",
      "Providing technical support (troubleshooting) if problems occur with employee work equipment.",
    ],
    lessons_learned: [
      "Learn that routine maintenance is much cheaper and more efficient than repairing total damage that causes operations to stop.",
      "Understand how to build infrastructure that can evolve with business growth without having to completely overhaul old systems",
    ],
    impact: [
      "Through inventory management and selecting the right technology, IT helps companies save long-term budgets",
      "With a stable system and minimal downtime, all divisions can work without technical interruptions, which directly increases company productivity.",
    ],
    isShow: true,
  },
  {
    position: "Frontend Developer",
    company: "Pt. Lumintu Logic Indonesia",
    logo: "/images/careers/lumintu-logic.webp",
    location: "Yogyakarta, Indonesia",
    location_type: "Onsite",
    type: "Part-time",
    start_date: "2021-06",
    end_date: "2025-6",
    industry: "Software House",
    link: "https://lumintu-logic.com/",
    responsibilities: [
      "Developed a responsive and interactive Learning Management System (LMS) using Astro.js, focusing on performance, modular component architecture, and maintainable frontend structure.",
      "Implemented Astro Islands architecture with dynamic islands, combining SSR and SSG for optimal performance and interactivity.",
      "Collaborated with cross-functional stakeholders to translate brand requirements and business goals into a consistent and user-friendly web experience.",
    ],
    lessons_learned: [
      "Gained hands-on experience with Astro Islands architecture, including managing dynamic islands alongside SSR and SSG rendering strategies.",
      "Learned to design a scalable and maintainable frontend architecture while balancing technical constraints with stakeholder and product requirements.",
      "Learned to integrate and manage third-party payment gateway services (Midtrans), including secure API interaction, payment flow orchestration, and robust error handling.",
    ],

    impact: [
      "Delivered a fast and responsive LMS with optimized initial load times through a hybrid rendering approach (SSR + SSG).",
      "Improved overall user experience and content accessibility by aligning frontend implementation with business and branding objectives.",
    ],
    isShow: false,
  },
  {
    position: "Frontend Developer",
    company: "Pt. Transisi Teknologi Mandiri",
    logo: "/images/careers/ttm.webp",
    location: "Yogyakarta, Indonesia",
    location_type: "Hybrid",
    type: "Full-time",
    start_date: "2020-9",
    end_date: "2021-4",
    industry: "Software House",
    link: "https://transisi.id/",
    responsibilities: [
      "Developed and maintained Module ERP system using HTML,CSS Framework, PHP , focusing on reusable components and clean, maintainable code.",
      "Collaborated closely with Product Managers, QA developers, and Backend developers to translate business processes and requirements into well-tested, functional ERP features.",
      "Translated Wireframe FIGMA into functional and user-friendly web interfaces.",
    ],
    lessons_learned: [
      "Gained a deeper understanding of ERP business workflows and how to implement them into modular and maintainable Laravel-based systems.",
      "Improved collaboration skills by working closely with Product Managers, QA, and Backend teams throughout the development and testing lifecycle.",
      "Enhanced ability to translate design wireframes into responsive, user-friendly interfaces while maintaining consistency with product requirements.",
    ],
    impact: [
      "Delivered stable and functional ERP modules that supported core business operations and internal workflows.",
      "Improved overall system usability and development efficiency through clean code practices and effective cross-functional collaboration.",
    ],
    isShow: true,
  },
];