export const CAREERS = [
  {
    position: "Staff IT",
    company: "Pt. Gisara Tantra Berkarya",
    logo: "/images/careers/gtb.webp",
    location: "Magelang, Indonesia",
    location_type: "Onsite",
    type: "Full-time",
    start_date: "2025-07",
    end_date: "2025-12",
    industry: "Manufacture",
    link: "https://www.gisaratantraberkarya.com/",
    responsibilities: [
      "Developed and maintained backend services using Golang for Parto.id's internal attendance application.",
      "Implemented efficient data handling and secure API integrations to support daily attendance workflows.",
      "Collaborated with frontend and product teams to ensure smooth functionality and seamless user experience.",
    ],
    lessons_learned: [
      "Deepened understanding of Go's concurrency model and Clean Architecture within a production environment.",
      "Gained hands-on experience in implementing Agile Scrum methodologies to streamline development workflows.",
      "Learned to collaborate effectively within a professional development team to achieve collective project goals.",
    ],
    impact: [
      "Developed core APIs for essential functionalities, including clock-in/clock-out systems, leave management (listing and requesting), and employee profile management (GET/UPDATE).",
      "Improved system reliability for internal tools by optimizing database queries for employee records and leave history.",
    ],
    isShow: true,
  },
  {
    position: "Frontend Web Developer",
    company: "Pt. Lumintu Logic Indonesia",
    logo: "/images/careers/lumintu-logic.webp",
    location: "Yogyakarta, Indonesia",
    location_type: "Onsite",
    type: "Part-time",
    start_date: "2021-07",
    end_date: "2025-7",
    industry: "Software House",
    link: "https://lumintu-logic.com/",
    responsibilities: [
      "Developed a responsive and interactive landing page using Next.js to promote company services and solutions.",
      "Ensured SEO optimization and fast performance by leveraging Next.js features such as static site generation.",
      "Collaborated with design and marketing teams to align web presence with brand identity.",
    ],
    lessons_learned: [
      "Mastered Next.js performance optimization (Core Web Vitals) and SEO best practices.",
      "Learned to bridge the gap between technical implementation and corporate branding requirements.",
    ],
    impact: [
      "Enhanced the company's digital visibility, leading to a significant increase in organic web traffic.",
      "Improved website loading speed, achieving a high Performance Score on Lighthouse.",
    ],
    isShow: false,
  },
  {
    position: "Frontend Web Developer",
    company: "Pt. Transisi Teknologi Mandiri",
    logo: "/images/careers/ttm.webp",
    location: "Yogyakarta, Indonesia",
    location_type: "Hybrid",
    type: "Full-time",
    start_date: "2020-12",
    end_date: "2021-12",
    industry: "School/Organization",
    link: "https://transisi.id/",
    responsibilities: [
      "Led the development of an internal RFID-based attendance system for HIMASI UNJA.",
      "Managed the technical team and oversaw the implementation of hardware-software integration.",
      "Ensured the system was user-friendly, secure, and met the organization's operational needs.",
    ],
    lessons_learned: [
      "Developed leadership skills and project management capabilities in a team setting.",
      "Gained hands-on experience in IoT integration and connecting hardware with web-based databases.",
    ],
    impact: [
      "Digitalized the organization's attendance process, eliminating paper waste and improving data accuracy.",
      "Successfully led a team of 5+ students to deliver the project on schedule.",
    ],
    isShow: true,
  },
];